#ifndef SPRITE_H
#define SPRITE_H

#include <stdint.h>

/* Auto-generated shader header: Sprite */
/* Generated by generate_shaders.py */

// Shader: Sprite.frag
const unsigned char SHADER_SPRITE_FRAG[] = {

};
const unsigned int SHADER_SPRITE_FRAG_SIZE = 0;

// Shader: Sprite.vert
const unsigned char SHADER_SPRITE_VERT[] = {

};
const unsigned int SHADER_SPRITE_VERT_SIZE = 0;

#endif /* SPRITE_H */
