//
// Created by Jake Rieger on 10/3/2026.
//
// The contract between a host (XED) and a game module: the game's own
// sources built as a DLL (<Game>Module.dll - see xen_add_game_module in
// XenGame.cmake) that the host loads to get the project's real Game subclass
// and components. GameModule.hpp is the host-side loader.
//
// A module exports three plain C functions, generated by XEN_GAME (or
// XEN_GAME_MODULE for a hand-written wWinMain) when the sources are compiled
// as a module (XEN_BUILDING_GAME_MODULE):
//
//   XenModule_GetInfo      - what the module was built against (checked first)
//   XenModule_CreateGame   - constructs the game in embedded mode
//   XenModule_DestroyGame  - destroys a game it created
//
// Its components need nothing extra: their XEN_COMPONENT registrars run when
// the DLL loads, into the same registry the host uses (the engine is a single
// shared Xen.dll), tagged with the module's ID so they can be removed again.

#pragma once

#include <Common/XenCommon.hpp>
#include <Common/Platform.hpp>

namespace Xen {
    class Game;

    namespace RHI {
        class IRenderDevice;
    }

    namespace PAK {
        struct AssetMountConfig;
    }

    /// @brief Bumped whenever ModuleInfo, EmbeddedGameArgs or the exported
    /// functions' signatures change, so a host refuses modules built against
    /// a different contract instead of crashing on them.
    constexpr u32 XEN_MODULE_ABI_VERSION = 1;

    /// @brief What a module was built against. Every field must match the host
    /// for the module to be usable - see GameModule::Load.
    struct ModuleInfo {
        u32 AbiVersion {0};
        /// XEN_ENGINE_VERSION at the module's compile time.
        const char* EngineVersion {nullptr};
        /// The game's display name (XEN_GAME's Title).
        const char* GameName {nullptr};
        /// The module's C++ runtime flavour. Objects (std::string, containers,
        /// components) cross the module boundary freely, which is only safe
        /// when both sides use the same runtime and iterator-debugging layout -
        /// a Debug module (/MDd) can't be loaded by a Release host (/MD).
        bool DebugRuntime {false};
        i32 IteratorDebugLevel {0};
    };

    /// @brief The embedded-mode Game constructor's arguments (see Game.hpp).
    /// Pointers, so the struct stays trivially passable across the C boundary.
    struct EmbeddedGameArgs {
        RHI::IRenderDevice* Device {nullptr};
        const PAK::AssetMountConfig* MountConfig {nullptr};
        u32 Width {0};
        u32 Height {0};
        const fs::path* ConfigRoot {nullptr};
    };

    namespace ModuleExports {
        constexpr const char* GetInfo     = "XenModule_GetInfo";
        constexpr const char* CreateGame  = "XenModule_CreateGame";
        constexpr const char* DestroyGame = "XenModule_DestroyGame";
    }  // namespace ModuleExports

    using ModuleGetInfoFn     = const ModuleInfo* (*)();
    using ModuleCreateGameFn  = Game* (*)(const EmbeddedGameArgs& Args);
    using ModuleDestroyGameFn = void (*)(Game* G);
}  // namespace Xen

// The runtime flavour of whichever binary expands this - the module (in
// XEN_GAME_MODULE) and the engine DLL (in GameModule.cpp) each evaluate it
// for themselves, which is the point of comparing them.
#ifdef _DEBUG
    #define XEN_MODULE_DEBUG_RUNTIME true
#else
    #define XEN_MODULE_DEBUG_RUNTIME false
#endif

#ifdef XEN_BUILDING_GAME_MODULE
    /// @brief Emits the module exports for GameClass. Only expands to anything
    /// when compiling the game as a module - in the game's executable it's
    /// empty, so the exe doesn't grow an export table. XEN_GAME already
    /// includes this; use it directly only next to a hand-written wWinMain.
    #define XEN_GAME_MODULE(GameClass, Title)                                                                          \
        extern "C" __declspec(dllexport) const Xen::ModuleInfo* XenModule_GetInfo() {                                  \
            static const Xen::ModuleInfo Info {                                                                        \
              .AbiVersion         = Xen::XEN_MODULE_ABI_VERSION,                                                       \
              .EngineVersion      = XEN_ENGINE_VERSION,                                                                \
              .GameName           = Title,                                                                             \
              .DebugRuntime       = XEN_MODULE_DEBUG_RUNTIME,                                                          \
              .IteratorDebugLevel = _ITERATOR_DEBUG_LEVEL,                                                             \
            };                                                                                                         \
            return &Info;                                                                                              \
        }                                                                                                              \
        extern "C" __declspec(dllexport) Xen::Game* XenModule_CreateGame(const Xen::EmbeddedGameArgs& Args) {          \
            return new GameClass(*Args.Device, *Args.MountConfig, Args.Width, Args.Height, *Args.ConfigRoot);          \
        }                                                                                                              \
        extern "C" __declspec(dllexport) void XenModule_DestroyGame(Xen::Game* G) {                                    \
            delete G;                                                                                                  \
        }
#else
    #define XEN_GAME_MODULE(GameClass, Title)
#endif
