[Actions]
# Put your custom action mappings here.
# Names cannot begin with a number or special character,
# and cannot contain any spaces. They are case-insensitive.
#
# To see the list of available keybinds:
# https://github.com/jakerieger/XENGINE/wiki/Keybinds
#
# Example:
# MoveUp = Key.W,Key.Up