[Engine]
# Path to scene file in Content directory
StartupScene = scenes/main.xscene

# Window mode to launch game in (windowed | borderless | fullscreen)
WindowMode = windowed

ResolutionX = 1280
ResolutionY = 720