"""
bin2c.py - Convert any file into a C/C++ header containing a byte array.

Example:
    python bin2c.py logo.png
        -> writes logo_png.h containing:
              LOGO_PNG_BYTES[]   (the file contents)
              LOGO_PNG_SIZE      (the length in bytes)
"""

import argparse
import os
import re
import sys


def make_identifier(filename: str) -> str:
    name = os.path.basename(filename).upper()
    name = re.sub(r"[^A-Z0-9]", "_", name)  # periods, dashes, spaces -> '_'
    if not name or name[0].isdigit():  # C identifiers can't start with a digit
        name = "_" + name
    return name


def format_bytes(data: bytes, per_line: int) -> str:
    if not data:
        # Zero-length arrays aren't valid C, so emit a single padding byte.
        return "    0x00"
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk))
    return ",\n".join(lines)


def generate_header(input_path: str, per_line: int) -> tuple[str, str]:
    with open(input_path, "rb") as f:
        data = f.read()

    base = make_identifier(input_path)
    bytes_name = f"{base}_BYTES"
    size_name = f"{base}_SIZE"
    guard = f"{base}_H"

    header = f"""\
/* Auto-generated by bin2c.py from "{os.path.basename(input_path)}". Do not edit. */
#pragma once

#include <stddef.h>

#ifdef __cplusplus
extern "C" {{
#endif

// clang-format off
static const size_t {size_name} = {len(data)};

static const unsigned char {bytes_name}[] = {{
{format_bytes(data, per_line)}
}};
// clang-format on

#ifdef __cplusplus
}}
#endif
"""
    return header, base


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert a file into a C/C++ header with a byte array and size constant."
    )
    parser.add_argument("input", help="Input file to embed")
    parser.add_argument(
        "-o", "--output",
        help="Output header path (default: <filename>_<ext>.h next to the input)",
    )
    parser.add_argument(
        "-w", "--width", type=int, default=12,
        help="Number of bytes per line (default: 12)",
    )
    args = parser.parse_args()

    if not os.path.isfile(args.input):
        print(f"error: '{args.input}' is not a file", file=sys.stderr)
        return 1
    if args.width < 1:
        print("error: --width must be at least 1", file=sys.stderr)
        return 1

    header, base = generate_header(args.input, args.width)

    output = args.output or os.path.join(
        str(os.path.dirname(args.input)), base.lower() + ".h"
    )
    with open(output, "w", newline="\n") as f:
        f.write(header)

    print(f"Wrote {output} ({base}_BYTES, {base}_SIZE)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
