#!/usr/bin/env python3
"""
Convert GLSL shader files to C header files with byte arrays.
- Fragment + Vertex pairs (.frag + .vert) → single header with both arrays
- Compute shaders (.comp) → individual header
"""

import os
import sys
from pathlib import Path
from collections import defaultdict


def sanitize_name(name):
    """Convert filename to valid C identifier."""
    name = ''.join(c if c.isalnum() or c == '_' else '_' for c in name)
    if name and name[0].isdigit():
        name = '_' + name
    return name or 'shader'


def file_to_hex_string(filepath):
    """Read file and return formatted hex string."""
    with open(filepath, 'rb') as f:
        data = f.read()

    formatted_lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_chunk = ', '.join(f'0x{byte:02x}' for byte in chunk)
        formatted_lines.append(f'    {hex_chunk}')

    return '\n'.join(formatted_lines), len(data)


def generate_header(base_name, shader_data):
    """Generate C header content from shader data."""
    guard_name = sanitize_name(base_name).upper() + '_H'

    header = f'''#ifndef {guard_name}
#define {guard_name}

#include <stdint.h>

/* Auto-generated shader header: {base_name} */
/* Generated by generate_shaders.py */

'''

    body = ''
    for shader_type, filepath in shader_data.items():
        hex_data, size = file_to_hex_string(filepath)
        var_prefix = 'SHADER_' + sanitize_name(base_name).upper()

        body += f'''// Shader: {filepath.name}
const unsigned char {var_prefix}_{shader_type.upper()}[] = {{
{hex_data}
}};
const unsigned int {var_prefix}_{shader_type.upper()}_SIZE = {size};

'''

    footer = f'''#endif /* {guard_name} */
'''

    return header + body + footer


def process_shaders(input_dir, output_dir=None):
    """Process GLSL shaders and generate headers."""
    input_path = Path(input_dir)

    if not input_path.is_dir():
        print(f"Error: {input_dir} is not a directory", file=sys.stderr)
        return

    if output_dir is None:
        output_dir = input_path

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Group shaders by base name
    shaders = defaultdict(dict)
    comp_shaders = {}

    for filepath in input_path.iterdir():
        if not filepath.is_file():
            continue

        suffix = filepath.suffix.lower()

        if suffix == '.comp':
            comp_shaders[filepath.stem] = filepath
        elif suffix in ['.frag', '.vert']:
            shaders[filepath.stem][suffix[1:]] = filepath  # Remove the dot

    generated_count = 0

    # Process fragment/vertex pairs
    for base_name, shader_files in shaders.items():
        if not shader_files:
            continue

        try:
            header_content = generate_header(base_name, shader_files)
            output_file = output_path / (base_name + '.h')

            with open(output_file, 'w') as f:
                f.write(header_content)

            types = ', '.join(shader_files.keys())
            print(f"✓ Generated {output_file.name} ({types})")
            generated_count += 1
        except Exception as e:
            print(f"✗ Error processing {base_name}: {e}", file=sys.stderr)

    # Process compute shaders
    for base_name, filepath in comp_shaders.items():
        try:
            shader_data = {'comp': filepath}
            header_content = generate_header(base_name, shader_data)
            output_file = output_path / (base_name + '.h')

            with open(output_file, 'w') as f:
                f.write(header_content)

            print(f"✓ Generated {output_file.name} (comp)")
            generated_count += 1
        except Exception as e:
            print(f"✗ Error processing {base_name}: {e}", file=sys.stderr)

    print(f"\nTotal headers generated: {generated_count}")


def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_shaders.py <shader_directory> [output_directory]")
        sys.exit(1)

    input_dir = sys.argv[1]
    output_dir = sys.argv[2] if len(sys.argv) > 2 else None

    process_shaders(input_dir, output_dir)


if __name__ == '__main__':
    main()
